spring:
  application:
    name: stress-platform-server
  datasource:
    url: jdbc:mysql://localhost:3306/forge?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  # Specify the DBMS
  jpa:
    database: MYSQL
  # Show or not log for each sql query
    show-sql: true
  # Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
  # Naming strategy
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  # stripped before adding them to the entity manager)
      properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  allow-bean-definition-overriding: true


  mvc:
    static-path-pattern: /static/**
